name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Render
    # Only run if CI workflow succeeded and it's on the main ok branch
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: app-jar
          path: quarkus-app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create a minimal Dockerfile for the runtime image
      - name: Create Dockerfile
        run: |
          echo "FROM amazoncorretto:21-alpine" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY quarkus-app/ /app/" >> Dockerfile    
          echo "EXPOSE 8080" >> Dockerfile
          echo 'CMD ["java", "-jar", "quarkus-run.jar"]' >> Dockerfile    

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quarkus-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quarkus-app:${{ github.sha }}

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X GET "https://api.render.com/deploy/$RENDER_SERVICE_ID?key=$RENDER_API_KEY"