## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

  publish-test-results:
    name: Publish Test Results
    needs: build
    runs-on: ubuntu-latest
    if: always()
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read

    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: test-results

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false