## A basic GitHub Actions workflow for your Quarkus application.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Publish Test Report
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          junit_files: "**/build/test-results/test/TEST-*.xml"
#          check_name: "Test Results"
#          comment_mode: "always"
#          fail_on: "nothing"
#          report_individual_runs: true
#          check_run_annotations: "all tests"
#          github_token: ${{ secrets.GITHUB_TOKEN }}